PWD = $(shell pwd)

#KERNEL_SRC = /root/workshop/project/lenovo/kernel/linux-3.10.35
KERNEL_SRC = /usr/src/linux-headers-3.13.0-32-generic/

obj-m := bwlist.o
bwlist-objs := bwlist_linux.o bwlist_ioctl.o bwlist_sess.o hashtb_comm.o bwlist_dnscache.o

